Development
AnkitKarnAK/racketstream-video-library pull request #1
Opened 2021-05-04 09:50 UTC by AnkitKarnAK

2021-05-26 12:24 UTC, Akshaay9 commented
Hey Ankit,
here`s few of my suggestion

Feature:-
1. Try to add features of `Like video and add to playlist` on individual videos too`
2. I am able to create multiple playlists with same name, so have a check on that in backend or in frontend

Code:-
1. On `api-request.js` file, u could have added one more case inside switch for POST, and used that for making all `get` and `post `
request intead of creating multiple functions like `getVideoFromServer` etc:-
2. In AuthContext, instead of creating multiple useStates, u could have used useReducer and an initialState to do perform and store all the necessary user details
3. (suggestion) try to write functions like `signupNewUser` and `signupNewUser` outside of your contextAPI, so that code would be easy to scale same thing goes for data-reducer.js.
4. On login page, it would be great if u could suggest what is the required password format, for users

Apart from that, everything looks Good.!
Akshay.

2021-05-27 11:34 UTC, uditkumar01 requested changes

2021-05-27 11:34 UTC, uditkumar01 commented on src/App.js
> +    if (isUserLogin) {
keep this function in a new file and import it from there

2021-05-27 11:34 UTC, uditkumar01 commented on src/components/WatchLaterItem.js
> +              (async () => {
make it a separate function

2021-05-27 11:34 UTC, uditkumar01 commented on src/components/pages/Signup.js
> +  const [userEmail, setUserEmail] = useState("");
u can use useReducer here as it has a lot of useEffect hooks

2021-05-27 11:34 UTC, uditkumar01 commented on src/components/pages/Signup.js
> +  const emailValidator = () => {
put these functions in separate utility file as these are generally used on both login and sign up components

2021-09-15 17:16 UTC, merged